package godot.codegen.constants

const val GENERATED_COMMENT = "THIS FILE IS GENERATED! DO NOT EDIT IT MANUALLY!"

val jvmMethodToNotGenerate = listOf(
    "ENGINEMETHOD_ENGINECLASS_OBJECT_FREE",
    "ENGINEMETHOD_ENGINECLASS_INTERPOLATEDCAMERA_SET_TARGET"
)