name: Create android export template
description: Creates an android godot export template
inputs:
  target:
    description: Export template's target
  base-path:
    description: Base path for downloaded libs
runs:
  using: composite
  steps:
    - name: Setup Godot dependencies
      uses: ./.github/actions/godot-deps

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Download android ${{ inputs.target }} export armv7 binary
      uses: actions/download-artifact@v3
      with:
        name: android-export-${{ inputs.target }}-binary-armv7
        path: ${{ inputs.base-path }}/armeabi-v7a

    - name: Download android ${{ inputs.target }} export arm64v8 binary
      uses: actions/download-artifact@v3
      with:
        name: android-export-${{ inputs.target }}-binary-arm64v8
        path: ${{ inputs.base-path }}/arm64-v8a

    - name: Download android ${{ inputs.target }} export x86_64 binary
      uses: actions/download-artifact@v3
      with:
        name: android-export-${{ inputs.target }}-binary-x86_64
        path: ${{ inputs.base-path }}/x86_64

    - name: Build android ${{ inputs.target }} export template
      shell: bash
      run: |
        cd platform/android/java/ && ./gradlew generateGodotTemplates