build/Bunnymark.x86_64 --bench=BunnymarkV2 --lang=gd
build/Bunnymark.x86_64 --bench=BunnymarkV2 --lang=kt
#build/Bunnymark.x86_64 --bench=BunnymarkV2 --lang=cs
build/Bunnymark.x86_64 --bench=BunnymarkV1Sprites --lang=gd
build/Bunnymark.x86_64 --bench=BunnymarkV1Sprites --lang=kt
#build/Bunnymark.x86_64 --bench=BunnymarkV1Sprites --lang=cs
build/Bunnymark.x86_64 --bench=BunnymarkV1DrawTexture --lang=gd
build/Bunnymark.x86_64 --bench=BunnymarkV1DrawTexture --lang=kt
#build/Bunnymark.x86_64 --bench=BunnymarkV1DrawTexture --lang=cs
build/Bunnymark.x86_64 --bench=BunnymarkV3 --lang=gd
build/Bunnymark.x86_64 --bench=BunnymarkV3 --lang=kt
#build/Bunnymark.x86_64 --bench=BunnymarkV3 --lang=cs
