#include "gdj_language.h"

#include "godot_jvm.h"
#include "jvm/wrapper/bridge/godot_print_bridge.h"
#include "jvm/wrapper/memory/memory_manager.h"
#include "lifecycle/paths.h"
#include "names.h"
#include "api/script/jvm_script_manager.h"
#include "api/script/jvm_script.h"

using namespace godot;

constexpr const char* GDJ_TEMPLATE = "// GENERATED BY THE GODOT EDITOR. DON'T FORGET TO CREATE A CORRESPONDING SOURCE "
                                     "FILE! OTHERWISE THIS FILE WILL BE DELETED UPON NEXT BUILD.\n"
                                     "\n"
                                     "registeredName = " CLASS_TEMPLATE "\n"
                                     "fqName = " GODOT_KOTLIN_PACKAGE "." CLASS_TEMPLATE "\n"
                                     "baseType = " BASE_TEMPLATE "\n"
                                     "supertypes = [\n"
                                     "    godot." BASE_TEMPLATE "\n"
                                     "]\n"
                                     "signals = []\n"
                                     "properties = []\n"
                                     "notifications = []\n"
                                     "functions = []\n";

GdjLanguage* GdjLanguage::get_instance() {
    static GdjLanguage* instance {memnew(GdjLanguage)};
    return instance;
}

void GdjLanguage::init() {
    GodotJvm::get_instance().initialize_up_to(GodotJvm::State::JVM_SCRIPTS_INITIALIZED);

#ifdef DEBUG_ENABLED
    GodotJvm::get_instance().validate_state();
#endif
}

void GdjLanguage::frame() {
    if (unlikely(GodotJvm::get_instance().state < GodotJvm::State::CORE_LIBRARY_INITIALIZED)) { return; }
    if (unlikely(GodotJvm::get_instance().user_configuration.disable_gc)) { return; }

    jni::Env env {jni::Jvm::current_env()};
    MemoryManager::get_instance().sync_memory(env);
}

void GdjLanguage::finish() {
    GodotJvm::get_instance().finalize_down_to(GodotJvm::State::NOT_STARTED);
}

void GdjLanguage::thread_enter() {
    jni::Jvm::attach();
}

void GdjLanguage::thread_exit() {
    jni::Jvm::detach();
}

String GdjLanguage::get_name() const {
    return GODOT_JVM_LANGUAGE_NAME;
}

String GdjLanguage::get_type() const {
    return GODOT_JVM_SCRIPT_NAME;
}

String GdjLanguage::get_extension() const {
    return GODOT_JVM_REGISTRATION_FILE_EXTENSION;
}

Vector<ScriptLanguage::StackInfo> GdjLanguage::debug_get_current_stack_info() {
    if (unlikely(GDKotlin::get_instance().state < GDKotlin::State::CORE_LIBRARY_INITIALIZED)) { return {}; }

    thread_local bool is_capturing_stacktrace {false};
    if (is_capturing_stacktrace) { return {}; }

    is_capturing_stacktrace = true;
    jni::Env env {jni::Jvm::current_env()};
    String stacktrace {bridges::GodotPrintBridge::get_instance().get_jvm_stacktrace(env)};
    is_capturing_stacktrace = false;

    Vector<StackInfo> stack_info;
    PackedStringArray frames {stacktrace.split("\n", false)};
    for (const String& frame : frames) {
        StackInfo info {};
        info.func = frame.strip_edges();
        stack_info.push_back(info);
    }
    return stack_info;
}

void GdjLanguage::get_recognized_extensions(List<String>* p_extensions) const {
    p_extensions->push_back(GODOT_JVM_REGISTRATION_FILE_EXTENSION);
}

bool GdjLanguage::handles_global_class_type(const String& p_type) const {
    return p_type == GODOT_JVM_SCRIPT_NAME;
}

bool GdjLanguage::supports_builtin_mode() const {
    return false;
}

Vector<String> GdjLanguage::get_reserved_words() const {
    static const Vector<String> ret = {
        "registeredName",
        "fqName",
        "baseType ",
        "supertypes",
        "signals",
        "properties",
        "notifications",
        "functions"
    };

    return ret;
}

bool GdjLanguage::is_control_flow_keyword(const String& p_keyword) const {
    return false;
}

Vector<String> GdjLanguage::get_comment_delimiters() const {
    static const Vector<String> ret = {"//"};
    return ret;
}

Vector<String> GdjLanguage::get_doc_comment_delimiters() const {return {};}

Vector<String> GdjLanguage::get_string_delimiters() const {return {};}

Ref<Script> GdjLanguage::make_template(const String& p_template, const String& p_class_name, const String& p_base_class_name) const {
    Ref<GdjScript> gdj_script;
    gdj_script.instantiate();
    String processed_template {
      String(GDJ_TEMPLATE).replace(BASE_TEMPLATE, p_base_class_name).replace(CLASS_TEMPLATE, p_class_name.to_pascal_case())
    };
    gdj_script->set_source_code(processed_template);
    gdj_script->set_name(p_class_name);
    return gdj_script;
}

Vector<ScriptLanguage::ScriptTemplate> GdjLanguage::get_built_in_templates(const StringName& p_object) {
    return {};
}

bool GdjLanguage::is_using_templates() {
    return false;
}
