#include "gdj_language.h"

#include "api/script/jvm_script_manager.h"
#include "api/script/language/gdj_script.h"
#include "godot_jvm.h"
#include "jvm/wrapper/bridge/godot_print_bridge.h"
#include "jvm/wrapper/memory/memory_manager.h"
#include "names.h"
#include "paths.h"

using namespace godot;

constexpr const char* GDJ_TEMPLATE = "// GENERATED BY THE GODOT EDITOR. DON'T FORGET TO CREATE A CORRESPONDING SOURCE "
                                     "FILE! OTHERWISE THIS FILE WILL BE DELETED UPON NEXT BUILD.\n"
                                     "\n"
                                     "registeredName = " CLASS_TEMPLATE "\n"
                                     "fqName = " GODOT_KOTLIN_PACKAGE "." CLASS_TEMPLATE "\n"
                                     "relativeSourcePath = \"\"\n"
                                     "baseType = " BASE_TEMPLATE "\n"
                                     "supertypes = [\n"
                                     "    godot." BASE_TEMPLATE "\n"
                                     "]\n"
                                     "signals = []\n"
                                     "properties = []\n"
                                     "functions = []\n";

GdjLanguage* GdjLanguage::get_instance() {
    static GdjLanguage* instance {memnew(GdjLanguage)};
    return instance;
}

void GdjLanguage::_init() {
    GodotJvm::get_instance().initialize_up_to(GodotJvm::State::JVM_SCRIPTS_INITIALIZED);

#ifdef DEBUG_ENABLED
    GodotJvm::get_instance().validate_state();
#endif
}

void GdjLanguage::_frame() {
    if (unlikely(GodotJvm::get_instance().state < GodotJvm::State::CORE_LIBRARY_INITIALIZED)) { return; }
    if (unlikely(GodotJvm::get_instance().user_configuration.disable_gc)) { return; }

    jni::Env env {jni::Jvm::current_env()};
    MemoryManager::get_instance().sync_memory(env);
}

void GdjLanguage::_finish() {
    GodotJvm::get_instance().finalize_down_to(GodotJvm::State::NOT_STARTED);
}

void GdjLanguage::_thread_enter() {
    // Godot calls this for every thread it spawns (worker-thread-pool workers, importer threads, etc.), for every
    // registered script language, regardless of whether any JVM script is in use. jni::Jvm::attach() unconditionally
    // dereferences its singleton instance, which is only set once JVM_STARTED is reached (see
    // JvmManager::initialize_or_get_jvm -> jni::Jvm::initialize) -- so any thread the engine spawns before that
    // point, or when the JVM failed to start at all, hits a null-pointer dereference here.
    if (unlikely(GodotJvm::get_instance().state < GodotJvm::State::JVM_STARTED)) { return; }
    jni::Jvm::attach();
}

void GdjLanguage::_thread_exit() {
    if (unlikely(GodotJvm::get_instance().state < GodotJvm::State::JVM_STARTED)) { return; }
    jni::Jvm::detach();
}

TypedArray<Dictionary> GdjLanguage::_debug_get_current_stack_info() {
    if (unlikely(GodotJvm::get_instance().state < GodotJvm::State::CORE_LIBRARY_INITIALIZED)) { return {}; }

    // Guards against the recursion this is otherwise prone to: an error hit while building the stacktrace ends up back in Godot's error-printing path, which asks for the current stack info again to attach it to that very error.
    thread_local bool is_capturing_stacktrace {false};
    if (is_capturing_stacktrace) { return {}; }

    is_capturing_stacktrace = true;
    jni::Env env {jni::Jvm::current_env()};
    String stacktrace {bridges::GodotPrintBridge::get_instance().get_jvm_stacktrace(env)};
    is_capturing_stacktrace = false;

    TypedArray<Dictionary> stack_info;
    PackedStringArray frames {stacktrace.split("\n", false)};
    for (const String& frame : frames) {
        Dictionary info;
        info["file"] = "";
        info["func"] = frame.strip_edges();
        info["line"] = 0;
        stack_info.push_back(info);
    }
    return stack_info;
}

String GdjLanguage::_get_name() const {
    return GODOT_JVM_LANGUAGE_NAME;
}

String GdjLanguage::_get_type() const {
    return GODOT_JVM_SCRIPT_NAME;
}

String GdjLanguage::_get_extension() const {
    return GODOT_JVM_REGISTRATION_FILE_EXTENSION;
}

PackedStringArray GdjLanguage::_get_recognized_extensions() const {
    PackedStringArray ret;
    ret.append(GODOT_JVM_REGISTRATION_FILE_EXTENSION);
    return ret;
}

bool GdjLanguage::_handles_global_class_type(const String& p_type) const {
    return p_type == GODOT_JVM_SCRIPT_NAME;
}

bool GdjLanguage::_has_named_classes() const {
    return true;
}

Object* GdjLanguage::_create_script() const {
    return memnew(GdjScript);
}

bool GdjLanguage::_supports_builtin_mode() const {
    return false;
}

PackedStringArray GdjLanguage::_get_reserved_words() const {
    static PackedStringArray reserved_words {
      "registeredName",
      "fqName",
      "relativeSourcePath ",
      "baseType ",
      "supertypes",
      "signals",
      "properties",
      "functions"
    };
    return reserved_words;
}

bool GdjLanguage::_is_control_flow_keyword(const String& p_keyword) const {
    return false;
}

PackedStringArray GdjLanguage::_get_comment_delimiters() const {
    static PackedStringArray delimiters {
      "//"
    };
    return delimiters;
}

PackedStringArray GdjLanguage::_get_doc_comment_delimiters() const { return {}; }

PackedStringArray GdjLanguage::_get_string_delimiters() const { return {}; }

Ref<Script> GdjLanguage::_make_template(const String& p_template, const String& p_class_name, const String& p_base_class_name) const {
    Ref<GdjScript> gdj_script;
    gdj_script.instantiate();
    String processed_template {
      String(GDJ_TEMPLATE).replace(BASE_TEMPLATE, p_base_class_name).replace(CLASS_TEMPLATE, p_class_name.to_pascal_case())
    };
    gdj_script->set_source_code(processed_template);
    gdj_script->set_name(p_class_name);
    return gdj_script;
}
