#ifndef GODOT_JVM_HASH_H
#define GODOT_JVM_HASH_H

// BE CAUTIOUS IF MODIFYING THIS VALUE, IT WILL BREAK THE UID OF ALL JVM SCRIPTS
static constexpr const char* UUID_HASH_SEED {"GODOT_JVM_f365477a"};

#endif // GODOT_JVM_HASH_H
