name: Setup JAVA_HOME
description: Setup the correct JAVA_HOME environment variable
inputs:
  version:
    description: 'Java version to use'
    default: '17'

runs:
  using: "composite"
  steps:
    - name: Setup JAVA_HOME on Linux or macOS
      if: runner.os != 'Windows'
      run: |
        if [ -n "$JAVA_HOME_${{ inputs.version }}_X64" ]; then
          echo "JAVA_HOME=$JAVA_HOME_${{ inputs.version }}_X64" >> $GITHUB_ENV
        else
          echo "JAVA_HOME=$JAVA_HOME_${{ inputs.version }}_arm64" >> $GITHUB_ENV
        fi
        echo "Set java home to: $JAVA_HOME"
      shell: bash

    - name: Setup JAVA_HOME on Windows
      if: runner.os == 'Windows'
      run: |
        if ($env:JAVA_HOME_${{ inputs.version }}_X64) {
          echo "JAVA_HOME=$env:JAVA_HOME_${{ inputs.version }}_X64" >> $env:GITHUB_ENV
        }
        else {
          echo "JAVA_HOME=$env:JAVA_HOME_${{ inputs.version }}_arm64" >> $env:GITHUB_ENV
        }
        echo "Set java home to: $env:JAVA_HOME"
      shell: pwsh