package godot.codegen.services.impl

const val AWAIT_FILE_NAME = "Await"
const val SIGNALS_FILE_NAME = "Signals"

const val CALLABLE_CLASS_BASENAME = "Callable"
const val JVM_ACTION_CLASS_BASENAME = "JvmAction"
const val JVM_FUNCTION_CLASS_BASENAME = "JvmFunction"
const val LAMBDA_CALLABLE_CLASS_BASENAME = "LambdaCallable"
const val LAMBDA_CONTAINER_CLASS_BASENAME = "LambdaContainer"
const val METHOD_CALLABLE_CLASS_BASENAME = "MethodCallable"
const val METHOD_STRING_CLASS_BASENAME = "MethodStringName"

const val SIGNAL_CLASS_BASENAME = "Signal"
const val SIGNAL_ARGUMENTS_CLASS_BASENAME = "SignalArguments"
const val SIGNAL_CONNECTORS_FILE_NAME = "SignalConnectors"

const val METHOD_NAME_AWAIT = "await"
const val METHOD_NAME_BIND = "bind"
const val METHOD_NAME_CALL = "call"
const val METHOD_NAME_CALL_DEFERRED = "callDeferred"
const val METHOD_NAME_CONNECT = "connect"
const val METHOD_NAME_CONNECT_LAMBDA = "connectLambda"
const val METHOD_NAME_CONNECT_METHOD = "connectMethod"
const val METHOD_NAME_CREATE = "create"
const val METHOD_NAME_CREATE_UNSAFE = "createUnsafe"
const val METHOD_NAME_DISCONNECT = "disconnect"
const val METHOD_NAME_EMIT = "emit"
const val METHOD_NAME_GET_VALUE = "getValue"
const val METHOD_NAME_INVOKE = "invoke"
const val METHOD_NAME_INVOKE_UNSAFE = "invokeUnsafe"
const val METHOD_NAME_PROMISE = "promise"
const val METHOD_NAME_SIGNAL = "signal"
const val METHOD_NAME_SUSPEND_CANCELLABLE_COROUTINE = "suspendCancellableCoroutine"
const val METHOD_NAME_TO_CALLABLE = "toCallable"
const val METHOD_NAME_RESUME = "resume"
const val METHOD_NAME_GET_VARIANT_CONVERTER = "getVariantConverter"

const val PROPERTY_NAME_DELEGATE = "delegate"

const val SUFFIX_UNSAFE = "Unsafe"
const val CANCELLABLE_CONTINUATION_CLASS_NAME = "CancellableContinuation"
const val INVALID_JVM_LAMBDA_EXCEPTION_CLASS_NAME = "InvalidJvmLambdaException"
const val OBJECT_CONNECT_FLAGS_CLASS_NAME = "Object.ConnectFlags"
const val K_PROPERTY_CLASS_NAME = "KProperty"
const val READ_ONLY_PROPERTY_CLASS_NAME = "ReadOnlyProperty"
