name: Determine Runner Tags
description: Determines runner tags based on the repository fork status

outputs:
  linux-runner-tag:
    description: Runner tag for Linux
    value: ${{ steps.set-linux-tag.outputs.tag }}
  macos-runner-tag:
    description: Runner tag for macOS
    value: ${{ steps.set-macos-tag.outputs.tag }}
  windows-runner-tag:
    description: Runner tag for Windows
    value: ${{ steps.set-windows-tag.outputs.tag }}

runs:
  using: composite
  steps:
    - name: Determine runner tag for Linux
      id: set-linux-tag
      shell: bash
      run: |
        if [ "${{ github.event.repository.fork }}" == "true" ]; then
          echo "tag=ubuntu-latest" >> "$GITHUB_OUTPUT"
        else
          echo "tag=self-hosted-linux" >> "$GITHUB_OUTPUT"
        fi

    - name: Determine runner tag for macOS
      id: set-macos-tag
      shell: bash
      run: |
        if [ "${{ github.event.repository.fork }}" == "true" ]; then
          echo "tag=macos-latest" >> "$GITHUB_OUTPUT"
        else
          echo "tag=self-hosted-macos" >> "$GITHUB_OUTPUT"
        fi

    - name: Determine runner tag for Windows
      id: set-windows-tag
      shell: bash
      run: |
        if [ "${{ github.event.repository.fork }}" == "true" ]; then
          echo "tag=windows-latest" >> "$GITHUB_OUTPUT"
        else
          echo "tag=self-hosted-windows" >> "$GITHUB_OUTPUT"
        fi