name: Determine Runner Tags
description: Determines runner tags based on the repository fork status

outputs:
  linux-runner-tags:
    description: Runner tags for Linux
    value: ${{ steps.set-linux-tag.outputs.tag }}
  macos-runner-tags:
    description: Runner tags for macOS
    value: ${{ steps.set-macos-tag.outputs.tag }}
  windows-runner-tags:
    description: Runner tags for Windows
    value: ${{ steps.set-windows-tag.outputs.tag }}

runs:
  using: composite
  steps:
    - name: Determine runner tag for Linux
      id: set-linux-tag
      shell: bash
      run: |
        if [ "${{ github.event.repository.fork }}" == "true" ]; then
          echo "tag=ubuntu-latest" >> "$GITHUB_OUTPUT"
        else
          {
            echo "tag=self-hosted";
            echo "tag=Linux";
          } >> "$GITHUB_OUTPUT"
        fi

    - name: Determine runner tag for macOS
      id: set-macos-tag
      shell: bash
      run: |
        if [ "${{ github.event.repository.fork }}" == "true" ]; then
          echo "tag=macos-latest" >> "$GITHUB_OUTPUT"
        else
          {
            echo "tag=self-hosted";
            echo "tag=macOS";
          } >> "$GITHUB_OUTPUT"
        fi

    - name: Determine runner tag for Windows
      id: set-windows-tag
      shell: bash
      run: |
        if [ "${{ github.event.repository.fork }}" == "true" ]; then
          echo "tag=windows-latest" >> "$GITHUB_OUTPUT"
        else
          {
            echo "tag=self-hosted";
            echo "tag=Windows";
          } >> "$GITHUB_OUTPUT"
        fi