name: 🐧 Assemble Linux
on:
  workflow_call:
    inputs:
      godot-kotlin-jvm-version:
        type: string
      godot-version:
        type: string
      build-version:
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux_assemble
  cancel-in-progress: true

jobs:
  create-linux-library-zip:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Create release library zip
            target: release
            arch: x86_64

          - name: Create debug library zip
            target: debug
            arch: x86_64
    steps:
      - name: Download ${{ matrix.target }} library
        uses: actions/download-artifact@v7
        with:
          name: ${{ matrix.target }}_linux_${{ matrix.arch }}
          path: godot-kotlin-jvm_gdextension_linuxbsd_${{ matrix.arch }}_${{ matrix.target }}_${{ inputs.godot-kotlin-jvm-version }}

      - name: Create Linux library zip
        run: |
          mkdir -p package/addons
          cp -R godot-kotlin-jvm_gdextension_linuxbsd_${{ matrix.arch }}_${{ matrix.target }}_${{ inputs.godot-kotlin-jvm-version }}/jvm package/addons/jvm
          cd package
          zip -r ../godot-kotlin-jvm_gdextension_linuxbsd_${{ matrix.arch }}_${{ matrix.target }}_${{ inputs.godot-kotlin-jvm-version }}.zip addons
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: godot-kotlin-jvm_gdextension_linuxbsd_${{ matrix.arch }}_${{ matrix.target }}_${{ inputs.godot-kotlin-jvm-version }}.zip
          path: godot-kotlin-jvm_gdextension_linuxbsd_${{ matrix.arch }}_${{ matrix.target }}_${{ inputs.godot-kotlin-jvm-version }}.zip
