name: Assemble Android
on:
  workflow_call:
    inputs:
      godot-version:
        type: string
      jvm-version:
        type: string

jobs:
  package-android-libraries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: '*_android_*'
          path: libraries
          merge-multiple: true
      - run: zip -q -9 -r godot-kotlin-jvm_gdextension_android.zip libraries
      - uses: actions/upload-artifact@v7
        with:
          name: godot-kotlin-jvm_gdextension_android.zip
          path: godot-kotlin-jvm_gdextension_android.zip
