name: Assemble iOS
on:
  workflow_call:
    inputs:
      godot-kotlin-jvm-version:
        type: string
      godot-version:
        type: string
      build-version:
        type: string

jobs:
  package-ios-libraries:
    runs-on: macos-15
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: '*_ios_*'
          path: libraries
          merge-multiple: true
      - run: zip -q -9 -r godot-kotlin-jvm_gdextension_ios.zip libraries
      - uses: actions/upload-artifact@v7
        with:
          name: godot-kotlin-jvm_gdextension_ios.zip
          path: godot-kotlin-jvm_gdextension_ios.zip
