name: iOS Builds
on:
  workflow_call:
    inputs:
      godot-version:
        type: string

jobs:
  ios-template:
    runs-on: macos-15
    permissions:
      contents: read
      actions: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - cache-name: debug_ios_arm64
            target: template_debug
          - cache-name: release_ios_arm64
            target: template_release
    env:
      SCONS_CACHE: ${{ github.workspace }}/.scons-cache
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - run: python -m pip install scons
      - uses: ./.github/actions/scons-cache
        with:
          mode: restore
          cache-name: ${{ matrix.cache-name }}
      - uses: ./.github/actions/gdextension-build
        with:
          platform: ios
          target: ${{ matrix.target }}
          scons-flags: arch=arm64
          target-path: artifact/addons/jvm/libs/
      - uses: ./.github/actions/scons-cache
        if: always()
        with:
          mode: save
          cache-name: ${{ matrix.cache-name }}
      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.cache-name }}
          path: artifact/addons
