name: ☕ Jvm Builds
on:
  workflow_call:
    inputs:
      jvm-version:
        type: string
      run-api-generator:
        type: boolean
        default: true
      run-ide-plugin:
        type: boolean
        default: true

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-jvm_build
  cancel-in-progress: true

jobs:
  build-api-generator:
    runs-on: ubuntu-latest
    name: Build API generator
    if: inputs.run-api-generator

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-swapfile: 'true'

      - name: Clone Godot JVM module.
        uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.jvm-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false
          cache-cleanup: always
          gradle-home-cache-excludes: |
            wrapper/dists
            caches/*/generated-gradle-jars
            daemon
            notifications

      - name: Build API generator
        run: kt/gradlew -p kt :api-generator:build

      - name: Upload api-generator artifact
        uses: actions/upload-artifact@v7
        with:
          name: jvm_api-generator
          path: kt/api-generator/build/libs/api-generator.jar

  build-ide-plugin:
    runs-on: ubuntu-latest
    name: Build and verify IDE plugin
    if: inputs.run-ide-plugin

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-swapfile: 'true'

      - name: Clone Godot JVM module.
        uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.jvm-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false
          cache-cleanup: always
          gradle-home-cache-excludes: |
            wrapper/dists
            caches/*/generated-gradle-jars
            daemon
            notifications

      - name: Build and verify IDE plugin
        run: kt/gradlew -p kt :godot-intellij-plugin:buildPlugin :godot-intellij-plugin:verifyPlugin

      - name: Upload intellij-plugin artifact
        uses: actions/upload-artifact@v7
        with:
          name: jvm_intellij-plugin
          path: kt/plugins/godot-intellij-plugin/build/distributions/godot-intellij-plugin-*.zip
