name: 🐧 Linux Builds
on:
  workflow_call:
    inputs:
      godot-version:
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux_build
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build editor release x86_64 (target=editor)
            cache-name: editor_release_linux_x86_64
            target: editor
            sconsflags: ''

          - name: Build editor debug (target=editor, debug_symbols=true )
            cache-name: editor_debug_linux_x86_64
            target: editor
            sconsflags: debug_symbols=true

          - name: Build editor dev (target=editor, dev_build=yes, debug_symbols=true )
            cache-name: editor_dev_linux_x86_64
            target: editor
            sconsflags: dev_build=yes debug_symbols=true

          - name: Build release template x86_64
            cache-name: export_template_release_linux_x86_64
            target: template_release
            sconsflags: ''

          - name: Build debug template x86_64
            cache-name: export_template_debug_linux_x86_64
            target: template_debug
            sconsflags: ''

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-swapfile: 'true'

      - name: Clone Godot Engine
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: ${{ inputs.godot-version }}

      - name: Clone Godot JVM module.
        uses: actions/checkout@v4
        with:
          path: modules/kotlin_jvm

      - name: Setup Godot build cache
        uses: ./modules/kotlin_jvm/.github/actions/scons-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ matrix.sconsflags }}
          platform: linuxbsd
          target: ${{ matrix.target }}

      - name: Prepare artifact
        if: ${{ matrix.artifact }}
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.cache-name }}
          path: "bin/*"
