name: macOS Builds
on:
  workflow_call:

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-macos_build
  cancel-in-progress: true

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          MATRIX='{"include":[
            {"name":"Build debug x86_64","cache-name":"debug_macos_x86_64","target":"editor","scons-flags":"arch=x86_64"},
            {"name":"Build release x86_64","cache-name":"release_macos_x86_64","target":"template_release","scons-flags":"arch=x86_64"},
            {"name":"Build debug arm64","cache-name":"debug_macos_arm64","target":"editor","scons-flags":"arch=arm64"},
            {"name":"Build release arm64","cache-name":"release_macos_arm64","target":"template_release","scons-flags":"arch=arm64"}
          ]}'
          echo "matrix=$(echo $MATRIX | jq -c '.')" >> $GITHUB_OUTPUT
  build-macos:
    needs: setup-matrix
    runs-on: macos-15
    name: ${{ matrix.name }}
    permissions:
      contents: read
      actions: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    env:
      SCONS_CACHE: ${{ github.workspace }}/.scons-cache
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - run: python -m pip install scons
      - uses: ./.github/actions/scons-cache
        with:
          mode: restore
          cache-name: ${{ matrix.cache-name }}
      - run: sh ./install_vulkan_sdk_macos.sh
      - uses: ./.github/actions/gdextension-build
        with:
          platform: macos
          target: ${{ matrix.target }}
          scons-flags: ${{ matrix.scons-flags }}
          target-path: artifact/addons/jvm/libs/
      - uses: ./.github/actions/scons-cache
        if: always()
        with:
          mode: save
          cache-name: ${{ matrix.cache-name }}
      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.cache-name }}
          path: artifact/addons
