name: Deploy docs

on:
  push:
    tags:
      - '\d+.\d+.\d+-\d+.\d+.\d+'

jobs:
  publish_stable_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Godot JVM module.
        uses: actions/checkout@v2
      - name: Retreive git tags
        run: |
          git fetch --all
      - name: Delete current stable tag
        run: |
          git tag -d stable
          git push origin --delete stable
      - name: Make current tag stable
        run: |
          git tag stable
          git push origin stable