#This workflow can only run on master! See the limitation mentioned in "Note:" here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run
name: Deploy Godot Editor Release
on:
  workflow_run:
    workflows: [ "Create Draft Release" ]
    types:
      - completed

env:
  SCONS_CACHE_MSVC_CONFIG: true

jobs:
  deploy-editor-release:
    strategy:
      matrix:
        name: [ Linux, MacOs-x64, MacOs-arm64, Windows ]
        include:
            # always use the oldest still supported LTS version of github actions. See: https://github.com/utopia-rise/godot-kotlin-jvm/issues/224
          - name: Linux
            os: ubuntu-20.04
            platform: x11
            binary: godot.linuxbsd.editor.x86_64
            cat_command: cat
            arch: x86_64
            target: editor
          - name: MacOs-x64
            os: macos-latest
            platform: macos
            binary: godot.macos.editor.x86_64
            cat_command: cat
            arch: x86_64
            target: editor
          - name: MacOs-arm64
            os: macos-latest
            platform: macos
            binary: godot.macos.editor.arm64
            cat_command: cat
            arch: arm64
            target: editor
          - name: Windows
            os: windows-2019
            platform: windows
            binary: godot.windows.editor.x86_64.exe
            cat_command: type
            arch: x86_64
            target: editor
    runs-on: ${{ matrix.os }}
    steps:
      # has to be the first step as the download url is only valid for 1 minute! See: https://stackoverflow.com/a/65049722
      - name: Get release infos from draft release
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create-draft-release.yaml
          workflow_conclusion: success

      - name: Create release information artifact
        if: matrix.platform == 'x11'
        uses: actions/upload-artifact@v3
        with:
          name: release-informations
          path: |
            release_url/release_url.txt
            godot_version/godot_version.txt
            godot_kotlin_jvm_version/godot_kotlin_jvm_version.txt

      - name: Save release infos as variables
        id: save_release_info
        run: |
          echo "::set-output name=upload_url::$(${{ matrix.cat_command }} release_url/release_url.txt)"
          echo "::set-output name=godot_version::$(${{ matrix.cat_command }} godot_version/godot_version.txt)"
          echo "::set-output name=godot_kotlin_jvm_version::$(${{ matrix.cat_command }} godot_kotlin_jvm_version/godot_kotlin_jvm_version.txt)"

      - name: Clone Godot Engine
        uses: actions/checkout@v2
        with:
          repository: godotengine/godot
          ref: 4.2.1-stable

      # TODO: remove once on godot 4.2.2 or newer!
      - name: Cherry pick macos fix
        run: |
          git fetch -a
          git config --global user.email "mario@super.com"
          git config --global user.name "Super Mario"
          git cherry-pick a2c1c01941a3dec3e2a361d9dc21bb0390efcbaf

      - name: Setup Vulkan SDK
        if: matrix.platform == 'macos'
        run: misc/scripts/install_vulkan_sdk_macos.sh
        shell: bash

      - name: Clone Godot JVM module.
        uses: actions/checkout@v2
        with:
          path: modules/kotlin_jvm
          submodules: recursive

      - name: Setup Godot dependencies
        uses: ./.github/actions/godot-deps
      - name: Fix scons version
        run: |
          python -m pip install scons==4.4.0

      - name: Fix scons version
        run: |
          python -m pip install scons==4.4.0

      # Upload cache on completion and check it out now
      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ github.job }}-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: Build ${{ matrix.os }} editor release app
        uses: ./.github/actions/godot-build
        with:
          sconsflags: arch=${{ matrix.arch }} -j${{ steps.cpu-cores.outputs.count }}
          platform: ${{ matrix.platform }}
          target: ${{ matrix.target }}

      - name: Build godot-bootstrap
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: modules/kotlin_jvm/kt/
          build-root-directory: modules/kotlin_jvm/kt/
          arguments: godot-library:build

      - name: Zip release
        if: matrix.platform != 'macos'
        uses: vimtor/action-zip@v1
        with:
          files: bin/${{ matrix.binary }} modules/kotlin_jvm/kt/godot-library/build/libs/godot-bootstrap.jar
          dest: godot-kotlin-jvm_editor_${{ matrix.platform }}_${{ steps.save_release_info.outputs.godot_kotlin_jvm_version }}.zip

      - name: Upload zip release
        if: matrix.platform != 'macos'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.save_release_info.outputs.upload_url }}
          asset_path: godot-kotlin-jvm_editor_${{ matrix.platform }}_${{ steps.save_release_info.outputs.godot_kotlin_jvm_version }}.zip
          asset_name: godot-kotlin-jvm_editor_${{ matrix.platform }}_${{ steps.save_release_info.outputs.godot_kotlin_jvm_version }}.zip
          asset_content_type: application/zip

      - name: Upload bootstrap jar
        if: matrix.platform == 'macos'
        uses: actions/upload-artifact@v3
        with:
          name: bootstrap-jar
          path: modules/kotlin_jvm/kt/godot-library/build/libs/godot-bootstrap.jar

      - name: Upload OSX binary
        if: matrix.platform == 'macos'
        uses: actions/upload-artifact@v3
        with:
          name: macos-editor-${{ matrix.target }}-binary-${{ matrix.arch }}
          path: bin/${{ matrix.binary }}

  create-macos-universal:
    needs: [ deploy-editor-release ]
    strategy:
      matrix:
        name: [ MacOs ]
        include:
          - name: MacOs
            os: macos-latest
            java-version: 11
            target: editor
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download release informations
        uses: actions/download-artifact@v3
        with:
          name: release-informations

      - name: Save release infos as variables
        id: save_release_info
        run: |
          echo "::set-output name=upload_url::$(cat release_url/release_url.txt)"
          echo "::set-output name=godot_version::$(cat godot_version/godot_version.txt)"
          echo "::set-output name=godot_kotlin_jvm_version::$(cat godot_kotlin_jvm_version/godot_kotlin_jvm_version.txt)"

      - name: Clone Godot JVM module.
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create OSX universal binary
        uses: ./.github/actions/create-macos-universal-binary
        with:
          amd-64-binary-artifact: macos-editor-${{ matrix.target }}-binary-x86_64
          amd-64-binary-name: godot.macos.${{ matrix.target }}.x86_64
          arm-64-binary-artifact: macos-editor-${{ matrix.target }}-binary-arm64
          arm-64-binary-name: godot.macos.${{ matrix.target }}.arm64
          universal-output-binary-name: godot.macos.${{ matrix.target }}.universal

      - name: Upload ${{ matrix.target }} macos universal artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-editor-${{ matrix.target }}-binary-universal
          path: godot.macos.${{ matrix.target }}.universal

  create-macos-editor-app:
    needs: [ create-macos-universal ]
    strategy:
      matrix:
        os: [ macos-latest ]
        include:
          - os: macos-latest
            java-version: 11
            target: editor
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download release informations
        uses: actions/download-artifact@v3
        with:
          name: release-informations

      - name: Save release infos as variables
        id: save_release_info
        run: |
          echo "::set-output name=upload_url::$(cat release_url/release_url.txt)"
          echo "::set-output name=godot_version::$(cat godot_version/godot_version.txt)"
          echo "::set-output name=godot_kotlin_jvm_version::$(cat godot_kotlin_jvm_version/godot_kotlin_jvm_version.txt)"

      - name: Clone Godot Engine
        uses: actions/checkout@v2
        with:
          repository: godotengine/godot
          ref: 4.2.1-stable

      - name: Get editor binary
        uses: actions/download-artifact@v3
        with:
          name: macos-editor-${{ matrix.target }}-binary-universal

      - name: Get bootstrap jar
        uses: actions/download-artifact@v3
        with:
          name: bootstrap-jar

      - name: Create MacOs editor app
        run: |
          cp -r misc/dist/macos_tools.app ./Godot.app
          mkdir -p Godot.app/Contents/MacOS
          cp godot.macos.${{ matrix.target }}.universal Godot.app/Contents/MacOS/Godot
          chmod +x Godot.app/Contents/MacOS/Godot
          cp godot-bootstrap.jar Godot.app/Contents/MacOS/
          chmod +x Godot.app/Contents/MacOS/godot-bootstrap.jar
          zip -q -9 -r godot-editor-macos.zip Godot.app
        shell: bash

      - name: Upload MacOs editor app
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.save_release_info.outputs.upload_url }}
          asset_path: godot-editor-macos.zip
          asset_name: godot-kotlin-jvm_editor_macos_${{ steps.save_release_info.outputs.godot_kotlin_jvm_version }}.zip
          asset_content_type: application/octet-stream
