#This workflow can only run on master! See the limitation mentioned in "Note:" here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run
name: Deploy Godot Editor Release
on:
  workflow_run:
    workflows: [ "Create Draft Release" ]
    types:
      - completed

env:
  SCONS_CACHE_MSVC_CONFIG: true

jobs:
  deploy-editor-release:
    strategy:
      matrix:
        name: [ Linux ]
        include:
          - name: Linux
            # always use the oldest still supported LTS version of github actions. See: https://github.com/utopia-rise/godot-kotlin-jvm/issues/224
            os: ubuntu-18.04
            platform: x11
            binary: godot.x11.opt.tools.64
            cat_command: cat
          - name: OSX
            os: macos-latest
            platform: osx
            binary: godot.osx.opt.tools.64
            cat_command: cat
          - name: Windows
            os: windows-2019
            platform: windows
            binary: godot.windows.opt.tools.64.exe
            cat_command: type
    runs-on: ${{ matrix.os }}
    steps:
      # has to be the first step as the download url is only valid for 1 minute! See: https://stackoverflow.com/a/65049722
      - name: Get release infos from draft release
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create-draft-release.yaml
          workflow_conclusion: success

      - name: Save release infos as variables
        id: save_release_info
        run: |
          echo "::set-output name=upload_url::$(${{ matrix.cat_command }} release_url/release_url.txt)"
          echo "::set-output name=godot_version::$(${{ matrix.cat_command }} godot_version/godot_version.txt)"
          echo "::set-output name=godot_kotlin_jvm_version::$(${{ matrix.cat_command }} godot_kotlin_jvm_version/godot_kotlin_jvm_version.txt)"

      - name: Configure dependencies
        if: matrix.platform == 'x11'
        run: |
          sudo apt-get update && sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
            libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm

      - name: Clone Godot Engine
        uses: actions/checkout@v2
        with:
          repository: godotengine/godot
          ref: 3.5-stable

      - name: Clone Godot JVM module.
        uses: actions/checkout@v2
        with:
          path: modules/kotlin_jvm
          submodules: recursive

      # Upload cache on completion and check it out now
      - name: Load .scons_cache directory
        id: template-release-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/${{matrix.platform}}/.scons_cache/
          key: ${{github.job}}-${{ steps.save_release_info.outputs.godot_version }}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{ steps.save_release_info.outputs.godot_version }}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{ steps.save_release_info.outputs.godot_version }}-${{github.ref}}
            ${{github.job}}-${{ steps.save_release_info.outputs.godot_version }}

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install -r modules/kotlin_jvm/requirements.txt

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: Build with editor release
        env:
          SCONS_CACHE: ${{github.workspace}}/${{matrix.platform}}/.scons_cache/
        run: scons platform=${{ matrix.platform }} target=release_debug -j${{ steps.cpu-cores.outputs.count }}

      - name: Build godot-bootstrap
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: modules/kotlin_jvm/kt/
          build-root-directory: modules/kotlin_jvm/kt/
          arguments: godot-library:build

      - name: Zip release
        uses: vimtor/action-zip@v1
        with:
          files: bin/${{ matrix.binary }} modules/kotlin_jvm/kt/godot-library/build/libs/godot-bootstrap.jar
          dest: godot-kotlin-jvm_editor_${{ matrix.platform }}_${{ steps.save_release_info.outputs.godot_kotlin_jvm_version }}.zip

      - name: Upload zip release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.save_release_info.outputs.upload_url }}
          asset_path: godot-kotlin-jvm_editor_${{ matrix.platform }}_${{ steps.save_release_info.outputs.godot_kotlin_jvm_version }}.zip
          asset_name: godot-kotlin-jvm_editor_${{ matrix.platform }}_${{ steps.save_release_info.outputs.godot_kotlin_jvm_version }}.zip
          asset_content_type: application/zip