#This workflow can only run on master! See the limitation mentioned in "Note:" here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run
name: Deploy Export Template Release
on:
  workflow_run:
    workflows: [ "Create Draft Release" ]
    types:
      - completed

env:
  SCONS_CACHE_MSVC_CONFIG: true

jobs:
  deploy-export-template-release:
    strategy:
      matrix:
        name: [ Linux ]
        include:
          - name: Linux
            # always use the oldest still supported LTS version of github actions. See: https://github.com/utopia-rise/godot-kotlin-jvm/issues/224
            os: ubuntu-20.04
            platform: x11
            binary: godot.x11.opt.64
            cat_command: cat
            arch: 64
          - name: OSX-x64
            os: macos-latest
            platform: osx
            binary: godot.osx.opt.64
            cat_command: cat
            arch: 64
          - name: OSX-arm64
            os: macos-latest
            platform: osx
            binary: godot.osx.opt.arm64
            cat_command: cat
            arch: arm64
          - name: Windows
            os: windows-2019
            platform: windows
            binary: godot.windows.opt.64.exe
            cat_command: type
            arch: 64
          - name: Android-armv7
            os: ubuntu-latest
            platform: android
            binary: android_release.apk
            cat_command: cat
            arch: armv7
            output_folder: platform/android/java/lib/libs/release/armeabi-v7a/
          - name: Android-armv8
            os: ubuntu-latest
            platform: android
            binary: android_release.apk
            cat_command: cat
            arch: arm64v8
            output_folder: platform/android/java/lib/libs/release/arm64-v8a/
    runs-on: ${{ matrix.os }}
    steps:
      # has to be the first step as the download url is only valid for 1 minute! See: https://stackoverflow.com/a/65049722
      - name: Get release infos from draft release
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create-draft-release.yaml
          workflow_conclusion: success

      - name: Create release information artifact
        if: matrix.platform == 'x11'
        uses: actions/upload-artifact@v3
        with:
          name: release-informations
          path: |
            release_url/release_url.txt
            godot_version/godot_version.txt
            godot_kotlin_jvm_version/godot_kotlin_jvm_version.txt

      - name: Save release infos as variables
        id: save_release_info
        run: |
          echo "::set-output name=upload_url::$(${{ matrix.cat_command }} release_url/release_url.txt)"
          echo "::set-output name=godot_version::$(${{ matrix.cat_command }} godot_version/godot_version.txt)"
          echo "::set-output name=godot_kotlin_jvm_version::$(${{ matrix.cat_command }} godot_kotlin_jvm_version/godot_kotlin_jvm_version.txt)"

      - name: Clone Godot Engine
        uses: actions/checkout@v2
        with:
          repository: godotengine/godot
          ref: 3.5.1-stable

      - name: Clone Godot JVM module.
        uses: actions/checkout@v2
        with:
          path: modules/kotlin_jvm
          submodules: recursive

      - name: Linux dependencies
        if: matrix.platform == 'x11'
        shell: bash
        run: |
          # Azure repositories are not reliable, we need to prevent azure giving us packages.
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update
          # The actual dependencies
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
              libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
              libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip

      - name: Setup Godot dependencies
        uses: ./.github/actions/godot-deps

      # Upload cache on completion and check it out now
      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ github.job }}-${{ matrix.platform }}-${{ matrix.arch }}

      - name: Set up JDK 11
        if: matrix.platform == 'android'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        if: matrix.platform == 'android'
        uses: android-actions/setup-android@v2

      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: Build release export template
        if: matrix.platform != 'android'
        uses: ./.github/actions/godot-build
        with:
          sconsflags: arch=${{ matrix.arch }} -j${{ steps.cpu-cores.outputs.count }}
          platform: ${{ matrix.platform }}
          target: release
          tools: false

      - name: Build android release export template binary
        if: matrix.platform == 'android'
        uses: ./.github/actions/godot-build
        with:
          sconsflags: android_arch=${{ matrix.arch }} -j${{ steps.cpu-cores.outputs.count }}
          platform: ${{ matrix.platform }}
          target: release
          tools: false

      - name: Upload android binary
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v3
        with:
          name: android-export-release-binary-${{ matrix.arch }}
          path: |
            **/${{ matrix.output_folder }}

      - name: Upload export template release
        if: matrix.platform != 'android' && matrix.platform != 'osx'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.save_release_info.outputs.upload_url }}
          asset_path: bin/${{ matrix.binary }}
          asset_name: ${{ matrix.binary }}
          asset_content_type: application/octet-stream

      - name: Upload OSX binary
        if: matrix.platform == 'osx'
        uses: actions/upload-artifact@v3
        with:
          name: osx-template-release-binary-${{ matrix.arch }}
          path: bin/${{ matrix.binary }}

  build-android-export-template:
    needs: [deploy-export-template-release]
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        include:
          - os: ubuntu-20.04
            java-version: 11
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download release informations
        uses: actions/download-artifact@v3
        with:
          name: release-informations

      - name: Save release infos as variables
        id: save_release_info
        run: |
          echo "::set-output name=upload_url::$(cat release_url/release_url.txt)"
          echo "::set-output name=godot_version::$(cat godot_version/godot_version.txt)"
          echo "::set-output name=godot_kotlin_jvm_version::$(cat godot_kotlin_jvm_version/godot_kotlin_jvm_version.txt)"

      - name: Clone Godot Engine
        uses: actions/checkout@v2
        with:
          repository: godotengine/godot
          ref: 3.5.1-stable

      - name: Clone Godot JVM module.
        uses: actions/checkout@v2
        with:
          path: modules/kotlin_jvm
          submodules: recursive

      - name: Build android export template
        uses: ./modules/kotlin_jvm/.github/actions/create-android-export-template
        with:
          target: release

      - name: Upload android export template release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.save_release_info.outputs.upload_url }}
          asset_path: bin/android_release.apk
          asset_name: android_release.apk
          asset_content_type: application/octet-stream

  create-macos-universal:
    needs: [deploy-export-template-release]
    strategy:
      matrix:
        os: [ macos-latest ]
        include:
          - os: macos-latest
            java-version: 11
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download release informations
        uses: actions/download-artifact@v3
        with:
          name: release-informations

      - name: Save release infos as variables
        id: save_release_info
        run: |
          echo "::set-output name=upload_url::$(cat release_url/release_url.txt)"
          echo "::set-output name=godot_version::$(cat godot_version/godot_version.txt)"
          echo "::set-output name=godot_kotlin_jvm_version::$(cat godot_kotlin_jvm_version/godot_kotlin_jvm_version.txt)"

      - name: Clone Godot JVM module.
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create OSX universal binary
        uses: ./.github/actions/create-osx-universal-binary
        with:
          amd-64-binary-artifact: osx-template-release-binary-64
          amd-64-binary-name: godot.osx.opt.64
          arm-64-binary-artifact: osx-template-release-binary-arm64
          arm-64-binary-name: godot.osx.opt.arm64
          universal-output-binary-name: godot.osx.opt.universal

      - name: Upload export template release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.save_release_info.outputs.upload_url }}
          asset_path: godot.osx.opt.universal
          asset_name: godot.osx.opt.universal
          asset_content_type: application/octet-stream