name: Deploy docs


on:
  workflow_call:
    inputs:
      runner-tag:
        type: string

jobs:
  publish_stable_tag:
    runs-on: ${{ inputs.runner-tags }}
    steps:
      - name: Clone Godot JVM module.
        uses: actions/checkout@v4
      - name: Retreive git tags
        run: |
          git fetch --tags
      - name: Delete current stable tag
        run: |
          git tag -d stable
          git push origin --delete stable
      - name: Make current tag stable
        run: |
          git tag stable
          git push origin stable
