name: 🐧 Linux Tests
on:
  workflow_call:
    inputs:
      godot-version:
        type: string
      jvm-version:
        type: string
      build-version:
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux_tests
  cancel-in-progress: true

jobs:
  test-linux:
    runs-on: ubuntu-22.04 # run tests on oldest ubuntu we still support. See build_linux.yml
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: debug tests
            extension-target: debug
            build-task: build

    steps:
      - name: Clone Godot JVM module.
        uses: actions/checkout@v6

      - uses: ./.github/actions/download-godot
        with:
          version: 4.7.1-stable
          platform: linux
          destination: harness/tests/bin

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.jvm-version }}

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: graalvm-community
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false
          cache-cleanup: always
          gradle-home-cache-excludes: |
            wrapper/dists
            caches/*/generated-gradle-jars
            daemon
            notifications

      - name: Download linux editor library
        uses: actions/download-artifact@v7
        with:
          name: ${{ matrix.extension-target }}_linux_x86_64
          path: './harness/tests/addons'

      - name: Build JVM tests project
        run: harness/tests/gradlew -p harness/tests/ ${{ matrix.build-task }}

      - name: Build Graal native image
        run: harness/tests/gradlew -p harness/tests/ buildGraalNativeImage

      - name: Import test project
        run: harness/tests/gradlew -p harness/tests/ importResources

      - name: Run JVM tests
        run: |
          cd harness/tests/
          chmod +x bin/godot.*
          jlink --add-modules java.base,java.logging --output jvm/jre-amd64-linux
          ./gradlew runGDTests
        timeout-minutes: 30

      - name: Run Graal native-image tests
        run: |
          cd harness/tests/
          ./gradlew runGraalGDTests
        timeout-minutes: 30
