name: 🪟 Windows Tests
on:
  workflow_call:
    inputs:
      godot-version:
        type: string
      jvm-version:
        type: string
      build-version:
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows_tests
  cancel-in-progress: true

jobs:
  test-windows:
    runs-on: windows-latest
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: dev tests
            target: dev
            jvm-target: debug
          - name: release tests
            target: release
            jvm-target: release

    steps:
      - name: Clone Godot JVM module.
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.jvm-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Download windows editor ${{ matrix.target }}
        uses: actions/download-artifact@v4
        with:
          name: editor_${{ matrix.target }}_windows_x86_64
          path: './harness/tests/bin'

      - name: Build tests project
        run: |
          harness/tests/gradlew -p harness/tests/ build -P${{ matrix.jvm-target }}

      - name: Run Tests
        run: |
          cd harness/tests/
          jlink --add-modules java.base,java.logging --output jvm/jre-amd64-windows
          ./gradlew runGutTests
        timeout-minutes: 30