name: 🍎 MacOS Exports Tests
on:
  workflow_call:
    inputs:
      godot-version:
        type: string
      jvm-version:
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos_exports_tests
  cancel-in-progress: true

jobs:
  test-macos-exports:
    runs-on: macos-15
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: release tests
            target: release
            jvm-target: release
            build-task: buildRelease

    steps:
      - name: Clone Godot JVM module.
        uses: actions/checkout@v6

      - uses: ./.github/actions/download-godot
        with:
          version: ${{ inputs.godot-version }}
          platform: macos
          destination: harness/tests/bin

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.jvm-version }}

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: graalvm-community
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false
          cache-cleanup: always
          gradle-home-cache-excludes: |
            wrapper/dists
            caches/*/generated-gradle-jars
            daemon
            notifications

      - name: Download macos editor library
        uses: actions/download-artifact@v7
        with:
          name: debug_macos_universal
          path: './harness/tests/addons'

      - name: Download macos export library
        uses: actions/download-artifact@v7
        with:
          name: release_macos_universal
          path: './harness/tests/addons'

      - name: Prepare export
        run: |
          chmod +x harness/tests/bin/godot.*
          mkdir -p harness/tests/export
          curl --fail --location https://github.com/godotengine/godot-builds/releases/download/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}_export_templates.tpz --output templates.tpz
          unzip -q templates.tpz -d templates
          template_version="${{ inputs.godot-version }}"
          template_version="${template_version//-/.}"
          template_directory="$HOME/Library/Application Support/Godot/export_templates/$template_version"
          mkdir -p "$template_directory"
          mv templates/templates/macos.zip "$template_directory/macos.zip"

      - name: Build JVM tests project
        run: harness/tests/gradlew -p harness/tests/ ${{ matrix.build-task }}

      - name: Build Graal native image
        run: harness/tests/gradlew -p harness/tests/ buildGraalNativeImage

      - name: Import test project
        run: harness/tests/gradlew -p harness/tests/ importResources

      - name: Create JRE
        run: |
          cd harness/tests/
          jlink --add-modules java.base,java.logging --output jvm/jre-arm64-macos
          mkdir jvm/jre-amd64-macos #create a fake jre dir for amd64 so the export is happy. The test will run on arm anyways

      - name: Export tests release
        run: |
          cd harness/tests/
          ./gradlew exportRelease
        timeout-minutes: 30

      - name: Extract app from dmg
        run: |
          cd harness/tests/export
          hdiutil attach tests.dmg
          cp -a /Volumes/Godot-JVM\ Tests/Godot-JVM\ Tests.app Godot-JVM\ Tests.app
          hdiutil detach /Volumes/Godot-JVM\ Tests
          cp -a ../jvm/jre-arm64-macos Godot-JVM\ Tests.app/Contents/PlugIns/

      - name: Run JVM exported tests
        run: cd harness/tests/; ./gradlew runExportedGDTests
        timeout-minutes: 30

      - name: Run Graal native-image exported tests
        run: cd harness/tests/; ./gradlew runExportedGraalGDTests
        timeout-minutes: 30
