name: 🪟 Windows Tests
on:
  workflow_call:
    inputs:
      godot-version:
        type: string
      jvm-version:
        type: string
      build-version:
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows_tests
  cancel-in-progress: true

jobs:
  test-windows:
    runs-on: windows-latest
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: dev tests
            target: dev
            bootstrap-target: debug
          - name: release tests
            target: release
            bootstrap-target: release

    steps:
      - name: Clone Godot JVM module.
        uses: actions/checkout@v4

      - name: Setup JAVA_HOME
        uses: ./.github/actions/setup-java-home
        with:
          version: ${{ inputs.jvm-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Setup gradle build cache
        uses: ./.github/actions/cache
        with:
          key: gradle_build_cache_tests
          path: |
            **/.gradle
            **/.kotlin
            **/.intellijPlatform
            **/build
          s3-host: ${{ secrets.S3_HOST }}
          s3-bucket: ${{ secrets.S3_BUCKET }}
          s3-user: ${{ secrets.S3_USER }}
          s3-password: ${{ secrets.S3_PASSWORD }}
          s3-user-readonly: ${{ secrets.S3_USER_READONLY }}
          s3-password-readonly: ${{ secrets.S3_PASSWORD_READONLY }}
        continue-on-error: true

      - name: Download windows editor ${{ matrix.target }}
        uses: actions/download-artifact@v4
        with:
          name: editor_${{ matrix.target }}_windows_x86_64
          path: './harness/tests/bin'

      - name: Download godot-bootstrap ${{ matrix.bootstrap-target }}
        uses: actions/download-artifact@v4
        with:
          name: jvm_godot-bootstrap_${{ matrix.bootstrap-target }}
          path: './harness/tests/bin'

      - name: Build tests project
        run: |
          harness/tests/gradlew -p harness/tests/ build -P${{ matrix.bootstrap-target }}

      - name: Run Tests
        run: |
          cd harness/tests/
          $JAVA_HOME/bin/jlink --add-modules java.base,java.logging --output jre-amd64-windows
          ./gradlew runGutTests
        timeout-minutes: 30