name: Master pipeline
on:
  schedule:
      - cron: '0 6 * * *' # run every day at 6am to prevent the cache from being cleared

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-trigger_on_push_master
  cancel-in-progress: true

jobs:
  setup-build-variables:
    # Fake job to define outputs which can be used in the other jobs
    name: 🛠️ Setup build variables
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Setup done"
    outputs: # defined here explicitly, so it only needs to be defined here. All other workflows can just reference it
      godot-jvm-version: "1.0.0-dev2"
      godot-version: "4.7.1-stable"
      jvm-version: "17"

  build-jvm:
    name: ☕ Build Jvm
    uses: ./.github/workflows/build_jvm.yml
    needs:
      - setup-build-variables
    with:
      jvm-version: ${{ needs.setup-build-variables.outputs['jvm-version'] }}

  build-android:
    if: ${{ false }}
    name: 🤖 Build Android
    uses: ./.github/workflows/build_android.yml
    needs:
      - setup-build-variables
    with:
      jvm-version: ${{ needs.setup-build-variables.outputs['jvm-version'] }}

  build-ios:
    if: ${{ false }}
    name: 🍏 Build iOS
    uses: ./.github/workflows/build_ios.yml
    needs:
      - setup-build-variables

  build-linux:
    name: 🐧 Build Linux
    uses: ./.github/workflows/build_linux.yml
    needs:
      - setup-build-variables

  build-macos:
    name: 🍎 Build macOS
    uses: ./.github/workflows/build_macos.yml
    needs:
      - setup-build-variables

  build-windows:
    name: 🪟 Build Windows
    uses: ./.github/workflows/build_windows.yml
    needs:
      - setup-build-variables

  assemble-android:
    if: ${{ false }}
    name: 🤖 Assemble android
    uses: ./.github/workflows/assemble_android.yml
    needs:
      - setup-build-variables
      - build-android
    with:
      jvm-version: ${{ needs.setup-build-variables.outputs['jvm-version'] }}

  assemble-macos:
    name: 🍎 Assemble macos
    uses: ./.github/workflows/assemble_macos.yml
    needs:
      - setup-build-variables
      - build-macos
    with:
      godot-jvm-version: ${{ needs.setup-build-variables.outputs['godot-jvm-version'] }}

  assemble-ios:
    if: ${{ false }}
    name: 🍏 Assemble ios
    uses: ./.github/workflows/assemble_ios.yml
    needs:
      - setup-build-variables
      - build-ios
    with:
      godot-jvm-version: ${{ needs.setup-build-variables.outputs['godot-jvm-version'] }}

  assemble-linux:
    name: 🐧 Assemble linux
    uses: ./.github/workflows/assemble_linux.yml
    needs:
      - setup-build-variables
      - build-linux
    with:
      godot-jvm-version: ${{ needs.setup-build-variables.outputs['godot-jvm-version'] }}

  assemble-windows:
    name: 🪟 Assemble windows
    uses: ./.github/workflows/assemble_windows.yml
    needs:
      - setup-build-variables
      - build-windows
    with:
      godot-jvm-version: ${{ needs.setup-build-variables.outputs['godot-jvm-version'] }}

  assemble-addon:
    name: 🤖+🍏+🐧+🍎+🪟 Assemble addon
    uses: ./.github/workflows/assemble_addon.yml
    needs:
      - setup-build-variables
      - build-linux
      - assemble-macos
      - build-windows
    with:
      godot-jvm-version: ${{ needs.setup-build-variables.outputs['godot-jvm-version'] }}
